<?php
    $viewModel = $block->getViewModel()
?>

<!-- Add CSS Variables -->
<style>
    :root {

        --primary-color: <?= $block->escapeHtml($viewModel->getStoreConfig('exodus/general/primary_colour')) ?>;
        --secondary-color: <?= $block->escapeHtml($viewModel->getStoreConfig('exodus/general/secondary_colour')) ?>;
        --tertiary-color: <?= $block->escapeHtml($viewModel->getStoreConfig('exodus/general/tertiary_colour')) ?>;

        --font-family: "Yuji Mai", sans-serif;


        /* OLD */

        --body-color: #f5f3ed;

        --footer-background-color: #EE4266;
        --footer-bottom-background-color: #FFD23F;

        --theme__color__primary: <?= $block->escapeHtml($viewModel->getStoreConfig('exodus/general/primary_colour')) ?>;
        --theme__color__secondary: ;
        --theme__color__primary-alt: #FFD23F;
        --theme__color__secondary: #540D6E;
    }
</style>

<!-- Add Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Yuji+Mai:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
